### ISSUE TITLE
Unable to sync Shopify products in Sanity, serverless functions error out.

### ISSUE THREAD

**Issue by jorytindall** [ndimatteo/HULL#10]
Hello!

This project is great, I appreciate your work and documentation! I'm having some issues getting the Sanity product sync working. I feel like I've been diligent about getting the correct API keys tokens and passwords, I've deployed to Vercel. 

I've tried sending a test webhook to the `product-update` API route and get errors in the Vercel dashboard. I'm not sure if that would be related to the issue though.

Here's a [repo](https://github.com/jorytindall/hull-test-demo) if that helps. 

Any insight on how to get this working or if there's something I'm missing in your documentation would be helpful!

Thank you!

**Comment by ndimatteo** [comment]
Hey there! Could you please share what errors you're getting in Vercel and a bit more about the issues you're encountering when trying to sync?

Also to test the sync'ing I'd recommend making an edit to one of your products on Shopify and seeing what the Vercel logs show. This will tell you a few things: (a) if it's actually triggering the webhook, and (b) any errors along the way.

Knowing that might give more insight into what's going on in your setup!

**Comment by jorytindall** [comment]
Wow, I feel slightly stupid now. That worked fine! I guess I wasn't thinking that products would only sync upon update, but that makes perfect sense. Thanks so much for you help and for bearing with me!

**Comment by ndimatteo** [comment]
no problem at all @jorytindall! This stuff is confusing in more ways than one. Glad that helped!

**Comment by mariussunde** [comment]
Hi!

I'm kinda stuck at the same level here, and I'm assuming there is an error in my Vercel variables, but I'm unfortunately a bit clueless as to where the error lies;

`15:05:04:03
2021-05-07T13:05:04.100Z	66b4bdd4-deba-49cb-b376-547a79397266	ERROR	TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at new Hmac (internal/crypto/hash.js:111:9)
    at Object.createHmac (crypto.js:147:10)
    at send (/var/task/.next/server/pages/api/shopify/product-update.js:86:77)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/var/task/node_modules/next/dist/next-server/server/router.js:25:67) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by ndimatteo** [comment]
Hey there @mariussunde!

It sounds like the `SHOPIFY_WEBHOOK_INTEGRITY` is not getting passed into the `/api/shopify/product-update` route where it's used [here](https://github.com/ndimatteo/HULL/blob/main/pages/api/shopify/product-update.js#L59).

This tells me it may not be added to your Vercel project properly. Make sure you've not only added your `.env` variables locally, but also on your deployed vercel instance (where the webhook is actually going to be triggering our API endpoint). 

Make sure you added them there and spelled everything correctly:
![image](https://user-images.githubusercontent.com/737188/117478751-8a15b680-af2d-11eb-8935-e2d0ca48c99a.png)

**Comment by ndimatteo** [comment]
Hey @mariussunde glad you were able to figure out what the issue was!

As for the demo products and sync'ing existing products:

- The product sync happens when the **shopify webhook is triggered**. The webhook gets triggered when an individual product is created, updated, or deleted. That's why the products you added _after_ everything was set up correctly sync'd! For your existing products all you need to do is make a small change to each of them in Shopify to trigger the webhook and re-sync them! I'd recommend using the bulk-edit tool in Shopify to make a small change like adding an extra space to the end of the Description field.
- The demo products are not tied to any Shopify store or the sync'ing mechanism. Simply delete them from your Sanity Studio to remove them :)

I hope that helps!

**Comment by beadlespouse** [comment]
Hey! I'm facing a similar issue here:

ERROR	TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "X-Shopify-Access-Token"

I'm 99% sure the SHOPIFY_ADMIN_API_TOKEN is set up correctly both locally and in vercel. Any ideas?

Thanks!!

**Comment by IMY2-studio** [comment]
Hey Nick!

Thanks so much for your work - I have been struggling to get this up and running for a little while now. I have triple checked my variables and added them to vercel 

<img width="913" alt="Screenshot 2022-11-10 at 10 03 31 pm" src="https://user-images.githubusercontent.com/102514959/201077204-c623d05e-fada-4dc4-b533-aa9ae7b196a6.png">

This is the vercel error from sending test notification

`[POST] /api/shopify/product-update

ERROR	TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at prepareSecretKey (node:internal/crypto/keys:580:11)
    at new Hmac (node:internal/crypto/hash:132:9)
    at Object.createHmac (node:crypto:162:10)
    at send (/var/task/.next/server/pages/api/shopify/product-update.js:117:79)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:252:36) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

Any suggestions on where I'm going wrong?
