### ISSUE TITLE
Cant build project 

### ISSUE THREAD

**Issue by wearedusa** [ndimatteo/HULL#32]
Hello!
In vercel and locally, I am getting these errors. What can I do to fix this?
**branch: marketing-starter**
```
03:48:30.840
info  - Generating static pages (0/3)
03:48:31.577
03:48:31.577
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
03:48:31.577
TypeError: Cannot read property 'modules' of null
03:48:31.577
    at Object.Home (/vercel/path0/.next/server/pages/index.js:2799:28)
03:48:31.577
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2523)
03:48:31.577
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.577
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.577
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:1576)
03:48:31.577
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:1767)
03:48:31.577
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.578
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:1576)
03:48:31.578
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.578
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.600
03:48:31.600
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
03:48:31.600
TypeError: Cannot read property 'seo' of null
03:48:31.600
    at Object.ErrorPage (/vercel/path0/.next/server/pages/404.js:5151:17)
03:48:31.600
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2523)
03:48:31.600
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.601
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.602
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:1576)
03:48:31.602
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:1767)
03:48:31.602
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.602
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:1576)
03:48:31.602
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.602
    at m (/vercel/path0/node_modules/preact-render-to-string/dist/commonjs.js:1:2667)
03:48:31.602
03:48:31.602
> Build error occurred
03:48:31.602
Error: Export encountered errors on following paths:
03:48:31.602
	/
03:48:31.602
	/404
03:48:31.602
    at /vercel/path0/node_modules/next/dist/export/index.js:31:1106
03:48:31.602
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
03:48:31.602
    at async /vercel/path0/node_modules/next/dist/build/index.js:43:49
03:48:31.602
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
03:48:31.602
    at async /vercel/path0/node_modules/next/dist/build/index.js:25:1475
03:48:31.603
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
03:48:31.603
info  - Generating static pages (3/3)
03:48:31.651
npm ERR! code ELIFECYCLE
03:48:31.651
npm ERR! errno 1
03:48:31.654
npm ERR! hull@2.0.0 build: `next build`
03:48:31.654
npm ERR! Exit status 1
03:48:31.654
npm ERR! 
03:48:31.654
npm ERR! Failed at the hull@2.0.0 build script.
03:48:31.654
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
03:48:31.660
03:48:31.660
npm ERR! A complete log of this run can be found in:
03:48:31.661
npm ERR!     /vercel/.npm/_logs/2021-07-25T00_48_31_654Z-debug.log
03:48:31.673
Error: Command "npm run build" exited with 1
````

**Comment by ndimatteo** [comment]
Hey there! It sounds like you haven't published any of the required documents in Sanity to properly generate the pages of your site. Make sure you have a connected sanity project with (at least) initial documents created for each singleton (all settings).

**Comment by ndimatteo** [comment]
Closing as I think this has been addressed.
