### ISSUE TITLE
Private App -> Custom App

### ISSUE THREAD

**Issue by dbrogers33** [ndimatteo/HULL#87]
I'm struggling to get my products to pull over from shopify to sanity. I believe the cause is that Shopify private apps were depreciated in [January 2022](https://help.shopify.com/en/manual/apps/private-apps). I've created a custom app but I don't think I'm picking the right variables.

**Comment by ndimatteo** [comment]
Hey there @dbrogers33! You are correct that Shopify refreshed their App UI, and private apps are now "custom apps". The concept is the same, but their UI flow is a bit different now.

I went through this with someone else in this thread, so hopefully this helps point you to the right areas: https://github.com/ndimatteo/HULL/issues/79#issuecomment-1035541851

Let me know if that helps! If there's something specific you're struggling with after reading through the above, let me know!

**Comment by dbrogers33** [comment]
Might be something different. I think my variables are correct. Took a look at the functions log and got the 'Session doesn't match project host'

`[POST] /api/shopify/product-update
15:01:01:83
/task/node_modules/get-it/lib-node/request/node-request.js:57:46)
    at /var/task/node_modules/get-it/lib-node/request/node-request.js:147:14
    at DestroyableTransform.<anonymous> (/var/task/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (events.js:519:28)
    at DestroyableTransform.emit (events.js:412:35)
    at endReadableNT (/var/task/node_modules/readable-stream/lib/_stream_readable.js:1010:12) {
  response: {
    body: {
      errorCode: 'SIO-401-AWH',
      statusCode: 401,
      message: 'Session does not match project host',
      error: 'Unauthorized'
    },
    url: 'https://t7sdip4d.api.sanity.io/v2021-03-25/data/query/production?query=*%5B_type%20%3D%3D%20%22productVariant%22%20%26%26%20productID%20%3D%3D%207663328198890%5D%7B%0A%20%20%20%20%20%20_id%0A%20%20%20%20%7D',
    method: 'GET',
    headers: {
      date: 'Tue, 12 Apr 2022 20:01:02 GMT',
      'content-type': 'application/json; charset=utf-8',
      'ratelimit-limit': '500',
      'ratelimit-remaining': '499',
      'x-ratelimit-limit-second': '500',
      'ratelimit-reset': '1',
      'x-ratelimit-remaining-second': '499',
      'content-length': '115',
      vary: 'Origin',
      xkey: 'project-t7sdip4d, project-t7sdip4d-production',
      via: '1.1 google',
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
      connection: 'close'
    },
    statusCode: 401,
    statusMessage: 'Unauthorized'
  },
  statusCode: 401,
  responseBody: '{\n' +
    '  "errorCode": "SIO-401-AWH",\n' +
    '  "statusCode": 401,\n' +
    '  "message": "Session does not match project host",\n' +
    '  "error": "Unauthorized"\n' +
    '}'
}
2022-04-12T20:01:02.661Z	0747673c-1c81-44a7-8d8a-1089243ed88d	ERROR	ClientError: Unauthorized - Session does not match project host
    at onResponse (/var/task/node_modules/@sanity/client/lib/http/request.js:27:13)
    at applyMiddleware (/var/task/node_modules/get-it/lib-node/util/middlewareReducer.js:14:23)
    at onResponse (/var/task/node_modules/get-it/lib-node/index.js:82:22)
    at /var/task/node_modules/get-it/lib-node/index.js:49:55
    at callback (/var/task/node_modules/get-it/lib-node/request/node-request.js:57:46)
    at /var/task/node_modules/get-it/lib-node/request/node-request.js:147:14
    at DestroyableTransform.<anonymous> (/var/task/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (events.js:519:28)
    at DestroyableTransform.emit (events.js:412:35)
    at endReadableNT (/var/task/node_modules/readable-stream/lib/_stream_readable.js:1010:12) {
  response: {
    body: {
      errorCode: 'SIO-401-AWH',
      statusCode: 401,
      message: 'Session does not match project host',
      error: 'Unauthorized'
    },
    url: 'https://t7sdip4d.api.sanity.io/v2021-03-25/data/query/production?query=*%5B_type%20%3D%3D%20%22productVariant%22%20%26%26%20productID%20%3D%3D%207663328198890%5D%7B%0A%20%20%20%20%20%20_id%0A%20%20%20%20%7D',
    method: 'GET',
    headers: {
      date: 'Tue, 12 Apr 2022 20:01:02 GMT',
      'content-type': 'application/json; charset=utf-8',
      'ratelimit-limit': '500',
      'ratelimit-remaining': '499',
      'x-ratelimit-limit-second': '500',
      'ratelimit-reset': '1',
      'x-ratelimit-remaining-second': '499',
      'content-length': '115',
      vary: 'Origin',
      xkey: 'project-t7sdip4d, project-t7sdip4d-production',
      via: '1.1 google',
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
      connection: 'close'
    },
    statusCode: 401,
    statusMessage: 'Unauthorized'
  },
  statusCode: 401,
  responseBody: '{\n' +
    '  "errorCode": "SIO-401-AWH",\n' +
    '  "statusCode": 401,\n' +
    '  "message": "Session does not match project host",\n' +
    '  "error": "Unauthorized"\n' +
    '}'
}
RequestId: 0747673c-1c81-44a7-8d8a-1089243ed88d Error: Runtime exited with error: exit status 1
Runtime.ExitError`

**Comment by ndimatteo** [comment]
It sounds like your deployed domain name is not authorized to make authenticated requests to the Sanity API.

Can you confirm if your deployed domain name that `/api/product-update` is using is added to the **CORS origins** section within your Sanity project with "allow credentials" permissions?

**Comment by dbrogers33** [comment]
<img width="866" alt="Screen Shot 2022-04-12 at 4 10 51 PM" src="https://user-images.githubusercontent.com/11230916/163055433-d393949c-5ff2-4fff-a44a-66cfab94babc.png">
<img width="859" alt="Screen Shot 2022-04-12 at 4 10 04 PM" src="https://user-images.githubusercontent.com/11230916/163055465-95ec62d6-4b25-4bf7-915e-54dbb698e8b6.png">

Also attempted a wildcard on the subdomain

**Comment by ndimatteo** [comment]
hmm, that's odd. Just to triple check, the project ID you've added your CORS Origin entry to is: `t7sdip4d` and the dataset you're using is `production`, correct?

If you wanted to add a wildcard, I'd suggest adding: `https://*.vercel.app` and see if that makes a difference.

If you're still getting the same authentication error it might be time to reach out to the [Sanity Community slack](https://slack.sanity.io/) for insight on their end. Sounds like it might be a bug with their API if that's the case.

**Comment by dbrogers33** [comment]
Product ID and dataset are both correct. I've tried the wildcard and still nothing. I'll give the slack channel a shot.

**Comment by ndimatteo** [comment]
Also, did you make sure you created a `SANITY_API_TOKEN` env variable on Vercel?

from the [readme](https://github.com/ndimatteo/HULL#4-nextjs):
- **`SANITY_API_TOKEN`** - Generate an API token for your Sanity project. Access your project from the Sanity Manage dashboard, and navigate to: "Settings" -> "API" -> "Add New Token" button. Make sure you give `read + write` access!

**Comment by ndimatteo** [comment]
That's the only other thing I can think of that would cause the Sanity Client to throw an authentication error.

The API Token is necessary to write data to your Sanity dataset, so if one is not set in your Vercel `env` variables, it won't work.

Also keep in mind, env variables need to be added before deployment to take effect. So if you added it after, make sure you redeploy.
