### ISSUE TITLE
Automatic Set Up failed

### ISSUE THREAD

**Issue by ansmlc** [ndimatteo/HULL#92]
Trying to do automatic set up as instructed by the docs using this URL:
https://www.sanity.io/create?template=ndimatteo/HULL

I get this error during deployment on Vercel:

```
> Build error occurred
Error: `dataset` must be provided to perform queries
at Object.exports.hasDataset (/vercel/path0/node_modules/@sanity/client/lib/validators.js:67:11)
at SanityClient.getDataUrl (/vercel/path0/node_modules/@sanity/client/lib/data/dataMethods.js:61:30)
at SanityClient._dataRequest (/vercel/path0/node_modules/@sanity/client/lib/data/dataMethods.js:167:20)
at SanityClient.fetch (/vercel/path0/node_modules/@sanity/client/lib/data/dataMethods.js:74:27)
at fetchSanityRedirects (/vercel/path0/next.config.js:16:29)
at Object.redirects (/vercel/path0/next.config.js:57:35)
at loadRedirects (/vercel/path0/node_modules/next/dist/lib/load-custom-routes.js:396:34)
at Object.loadCustomRoutes [as default] (/vercel/path0/node_modules/next/dist/lib/load-custom-routes.js:457:9)
at Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:26)
Error: Command "npm run build" exited with 1
```

**Comment by ndimatteo** [comment]
Hey there @ansmlc I just ran a test of the automatic set up on Sanity and did not run into this issue.

It looks like something may have happened with the creation of your Sanity project's dataset and/or the Vercel `.env` variable associated with it.

This sounds like a temporary error on the automation side of things with Sanity and/or Vercel, but if you keep experiencing this feel free to provide any more info you can and reach out to the Sanity community slack since it may be an issue with their automation tool.
